apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dashboard-cluster-role
  name: cluster-role
rules:
- apiGroups: 
  - ""
  - extentions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
