apiVersion: v1
kind: Pod
metadata:
  name: kubia-2
spec:
# Apply SecurityContext for entire pod
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  volumes:
  - name: security-context-vol
    emptyDir: {}
  containers:
  - name: security-context-cont
    image: stv707/kubia:v14
    volumeMounts:
    - name: security-context-vol
      mountPath: /data/test
    securityContext:
      allowPrivilegeEscalation: false