apiVersion: v1
kind: Service
metadata:
  name: javaappsvc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: javaapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: javaapp
        image: stv707/javaapp:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javaappingress
  annotations:
   #Comment the nginx class to use Azure http routing , uncomment addon-http-application-routing 
   #kubernetes.io/ingress.class: "nginx"
   kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    # Change to app1.<azure_dns> 
  - host: java.c66361a4adc2449aae2b.eastasia.aksapp.io

    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service: 
            name: javaappsvc
            port: 
              number: 80