apiVersion: v1
kind: LimitRange
metadata:
  name: itns-limit
  namespace: itappns
spec:
  limits:
  - type: Pod
    min:
      cpu: 500m
      memory: 512Mi
    max:
      cpu: 900m
      memory: 1024Mi
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 128Mi
    min:
      cpu: 50m
      memory: 5Mi
    max:
      cpu: 900m
      memory: 1024Mi
    maxLimitRequestRatio:
      cpu: 4
      memory: 10
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 3Gi
